### ISSUE TITLE
is this mirror stale?

### ISSUE THREAD

**Issue by curlup** [postgres-ai/postgres-checkup#155]
Is this one behind the one on gitlab.com? 
Which one should be used? 

PS may be set up a push mirroring from there?

**Comment by NikolayS** [comment]
Yep, it's definitely far behind. Looks like GitLab mirroring feature's failure.

> PS may be set up a push mirroring from there?

We've fully migrated from GitHub to GitLab some time ago.  So we don't use GitHub on daily basis anymore.

We'll need to fix it since people look at github anyway. Or maybe delete the contents here and leave a notice where to find it. What do you think @curlup, which approach would serve better?
